Python Web Developer-Course/Class1/1.py/addressbook/addressbook/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
import contacts.views
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'addressbook.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$',contacts.views.ListContactView.as_view(),name='contacts-list',),
    url(r'^new$', contacts.views.CreateContactView.as_view(),name='contacts-new',),
    url(r'edit/(?P<pk>\d+)/$',contacts.views.UpdateContactView.as_view(),name='contacts-edit'),
    url(r'^delete/(?P<pk>\d+)/$', contacts.views.DeleteContactView.as_view(),name='contacts-delete'),
    url(r'^(?P<pk>\d+)/$', contacts.views.ContactView.as_view(),name='contacts-view',),
    url(r'^delete/(?P<pk>\d+)/$', contacts.views.DeleteContactView.as_view(),name='contacts-delete'),
    url(r'^contacts-edit-addresses/(?P<pk>\d+)/$', contacts.views.UpdateContactView.as_view(), name='contacts-edit-addresses'),

    url(r'^edit/(?P<pk>\d+)/addresses$', contacts.views.EditContactAddressView.as_view(),
        name='contacts-edit-addresses',),
    url(r'^login/$', 'django.contrib.auth.views.login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout'),

    url(r'^',include('restapi.urls')),

)

Python Web Developer-Course/Class1/1.py/addressbook/restapi/urls.py
from django.conf.urls import url
from restapi import views
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns = [
    url(r'^restapi/$', views.SnippetList.as_view()),
    #url(r'^restapi/(?P<pk>[0-9]+)/$', views.SnippetDetail.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

Python Web Developer-Course/Class1/1.py/addressbook/contacts/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User


class Contact(models.Model):
    first_name = models.CharField(
        max_length=255,
    )
    last_name = models.CharField(
        max_length=255,
    )
    email = models.EmailField()

    owner = models.ForeignKey(User)

    def __str__(self):
        return ' '.join([self.first_name,self.last_name])

    def get_absolute_url(self):

        return reverse('contacts-view', kwargs={'pk': self.id})


class Address(models.Model):

    contact = models.ForeignKey(Contact)
    address_type = models.CharField(
        max_length=10,
    )

    address = models.CharField(
        max_length=255,
    )
    city = models.CharField(
        max_length=255,
    )
    state = models.CharField(
        max_length=2,
    )
    postal_code = models.CharField(
        max_length=20,
    )

    class Meta:
        unique_together = ('contact', 'address_type',)

Python Web Developer-Course/Class1/1.py/addressbook/restapi/models.py
from django.db import models

class Snippet(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=100, blank=True, default='')
    code = models.TextField()
    linenos = models.BooleanField(default=False)

    class Meta:
        ordering = ('created',)

Python Web Developer-Course/Class1/1.py/addressbook/contacts/forms.py
from django import forms
from django.core.exceptions import ValidationError

from contacts.models import Contact

class ContactForm(forms.ModelForm):

    confirm_email = forms.EmailField(
        label= "Confirm Email",
        required=True,
    )

    class Meta:
        model = Contact

    def __init__(self, *args, **kwargs):

        if kwargs.get('instance'):
            email = kwargs['instance'].email
            kwargs.setdefault('initial', {})['confirm_email'] = email

        return super(ContactForm, self).__init__(*args, **kwargs)

    def clean(self):

        if (self.cleaned_data.get('email') !=
            self.cleaned_data.get('confirm_email')):

            raise ValidationError(
                "Email addresses must match."
            )

        return self.cleaned_data


from django.forms.models import inlineformset_factory

from contacts.models import (
    Contact,
    Address,
)

# inlineformset_factory creates a Class from a parent model (Contact)
# to a child model (Address)
ContactAddressFormSet = inlineformset_factory(
    Contact,
    Address,
)

Python Web Developer-Course/Class1/1.py/addressbook/contacts/views.py
# coding:utf-8
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import View, ListView, CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse
from .models import Contact
from django.views.generic import DetailView
import forms
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.core.exceptions import PermissionDenied
from django.core.exceptions import ObjectDoesNotExist
# FBV
# def hello_world(request):
#    return HttpResponse("hello,workd")

# CBV

class ContactOwnerMixin(object):

    def get_object(self, queryset=None):
        """Returns the object the view is displaying.

        """
        if queryset is None:
            queryset = self.get_queryset()

        pk = self.kwargs.get(self.pk_url_kwarg, None)
        queryset = queryset.filter(
            pk=pk,
            owner=self.request.user,
        )

        try:
            obj = queryset.get()
        except ObjectDoesNotExist:
            raise PermissionDenied

        return obj

class LoggedInMixin(object):

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LoggedInMixin, self).dispatch(*args, **kwargs)


class MyVIew(View):

    def get(self, request):
        return HttpResponse("hello,world")

class ListContactView(LoggedInMixin, ListView):

    model = Contact
    template_name = 'contact_list.html'

    def get_queryset(self):
        return Contact.objects.filter(owner=self.request.user)

class CreateContactView(CreateView):

    model = Contact
    template_name = 'contacts/edit_contact.html'
    form_class =  forms.ContactForm

    def get_success_url(self):
        return reverse('contacts-list')

    def get_context_data(self, **kwargs):
        context = super(CreateContactView, self).get_context_data(**kwargs)
        context['action'] = reverse('contacts-new')
        return context

class UpdateContactView(UpdateView):

    model = Contact
    template_name = 'contacts/edit_contact.html'
    form_class =  forms.ContactForm

    def get_success_url(self):
        return reverse('contacts-list')

    def get_context_data(self, **kwargs):
        context = super(UpdateContactView, self).get_context_data(**kwargs)
        #print context
        context['action'] = reverse('contacts-edit',kwargs={'pk':self.get_object().id})
        print context['action']
        return context

class DeleteContactView(DeleteView):

    model = Contact
    template_name = 'contacts/delete_contact.html'

    def get_success_url(self):
        return reverse('contacts-list')


class ContactView(LoggedInMixin, ContactOwnerMixin, DetailView):

    model = Contact
    template_name = 'contacts/contact.html'


class EditContactAddressView(UpdateView):

    model = Contact
    template_name = 'edit_addresses.html'
    form_class = forms.ContactAddressFormSet

    def get_success_url(self):

        # redirect to the Contact view.
        return self.get_object().get_absolute_url()

Python Web Developer-Course/Class1/1.py/addressbook/restapi/views.py
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from rest_framework import status
from rest_framework.views import APIView
from rest_framework.renderers import JSONRenderer
from rest_framework.decorators import api_view
from rest_framework.response import Response
from restapi.models import *
from restapi.serializers import SnippetSerializer
from rest_framework import generics
from django.http import Http404

class JSONResponse(HttpResponse):

    def __init__(self, data, **kwargs):
        content = JSONRenderer().render(data)
        kwargs['content_type'] = 'application/json'
        super(JSONResponse, self).__init__(content, **kwargs)


class SnippetList(generics.ListAPIView):

    serializer_class = SnippetSerializer

    def get_queryset(self):
        queryset = Snippet.objects.all()
        code = self.request.query_params.get('code', None)
        if code is not None:
            queryset = [ queryset.filter(code=code).values('id').last() ]
            print queryset
        else:
            raise Http404
            #print 1111
            #content = {'please move along': 'nothing to see here'}
            #return Response(content, status=status.HTTP_404_NOT_FOUND)
        return queryset

Python Web Developer-Course/Class1/1.py/addressbook/templates/base.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

    <div>
      {{ user }}
      {% if user.is_anonymous %}
      <a href="{% url 'django.contrib.auth.views.login' %}">login</a>
      {% else %}
      <a href="{% url 'django.contrib.auth.views.logout' %}">logout</a>
      {% endif %}
    </div>
    {% block content %}
    {% endblock %}
</body>
</html>

Python Web Developer-Course/Class1/1.py/addressbook/templates/contacts/contact.html
{% extends "base.html" %}

{% block content %}

<h1>{{ contact }}</h1>

<p>Email: {{ contact.email }}</p>

<ul>
{% for address in contact.address_set.all %}
   <li>{{ address.address }}<br/>
       {{ address.city }} {{ address.state }}<br/>
       {{ address.postal_code }}
   </li>
{% endfor %}
</ul>

{% endblock %}

Python Web Developer-Course/Class1/1.py/addressbook/templates/contacts/contact_list.html
{% extends 'base.html' %}

{% block content %}
<h1>Contacts</h1>

<ul>
  {% for contact in object_list %}
    <li class="contact">
        <a href="{{ contact.get_absolute_url }}">{{ contact }}</a>
      <a href="{% url "contacts-edit" pk=contact.id %}">edit</a>
    </li>
  {% endfor %}
</ul>

<a href="{% url 'contacts-new' %}" >add contact</a>
{% endblock %}

Python Web Developer-Course/Class1/1.py/addressbook/templates/contacts/delete_contact.html
{% extends "base.html" %}

{% block content %}

<h1>Delete Contact</h1>

<p>Are you sure you want to delete the contact {{ contact }}?</p>

<form action="{% url "contacts-delete" pk=contact.id %}" method="POST">
  {% csrf_token %}

  <input type="submit" value="Yes, delete." />
  <a href="{% url "contacts-list" %}">No, cancel.</a>
</form>

{% endblock %}

Python Web Developer-Course/Class1/1.py/addressbook/templates/contacts/edit_contact.html
{% extends "base.html" %}

{% block content %}

{% if contact.id %}
<h1>Edit Contact</h1>
{% else %}
<h1>Add Contact</h1>
{% endif %}

<form action="{{ action }}" method="POST">
  {% csrf_token %}
  {% if form.non_field_errors %}
    <ul>
      {% for error in form.non_field_errors %}
        <li>{{ error }}</li>
      {% endfor %}
    </ul>
  {% endif %}
  {% for field in form %}
  <div id="{{ field.auto_id }}_container">
    {{ field.help_text }}
    <div>
      {{ field.label_tag }} {{ field }}
    </div>
    <div id="{{ field.auto_id }}_errors">
      {{ field.errors }}
    </div>
  </div>
  {% endfor %}

  <input id="save_contact" type="submit" value="Save" />
</form>

{% if contact.id %}
<a href="{% url "contacts-edit-addresses" pk=contact.id %}">
  Edit Addresses
</a>
<a href="{% url "contacts-delete" pk=contact.id %}">Delete</a>
{% endif %}

<a href="{% url "contacts-list" %}">back to list</a>

{% endblock %}

Python Web Developer-Course/Class1/1.py/addressbook/templates/edit_addresses.html
{% extends "base.html" %}

{% block content %}

<h1>Edit Addresses</h1>

<p>Editing addresses for {{ contact }}</p>

<form action="{% url "contacts-edit-addresses" pk=contact.id %}"
      method="POST">
    {% csrf_token %}
    {{ form.management_form }}
    {% for address_form in form %}

        <ul>
        {{ address_form.as_ul }}
        </ul>

    {% endfor %}

    <input type="submit" value="Save" />
</form>

{% endblock %}